# Generated by Django 4.2.30 on 2026-04-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(help_text="Например: 'article', 'report'", max_length=100)),
                ('action', models.CharField(help_text="Например: 'create', 'read', 'update'", max_length=50)),
                ('allowed', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.role')),
            ],
            options={
                'db_table': 'rbac_permission_rule',
                'unique_together': {('role', 'resource', 'action')},
            },
        ),
    ]
